server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:336/tensquare_base?characterEncoding=utf-8
    data-username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true
